CREATE TABLE ITEM (
  ID bigint generated by default as identity,
  NAME VARCHAR(100) not null,
  COLOR VARCHAR(100) not null,
  SIZE VARCHAR(100) not null,
  AMOUNT DECIMAL not null,
  CURRENCY VARCHAR(5) not null,
  ORDER_ID BIGINT,

  PRIMARY KEY(ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID)
)